/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGoogleCallbackRouteImport } from './routes/api/google/callback'
import { Route as ApiJobsPdfRouteImport } from './routes/api/jobs/pdf'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGoogleCallbackRoute = ApiGoogleCallbackRouteImport.update({
  id: '/api/google/callback',
  path: '/api/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJobsPdfRoute = ApiJobsPdfRouteImport.update({
  id: '/api/jobs/pdf',
  path: '/api/jobs/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/jobs/pdf': typeof ApiJobsPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/jobs/pdf': typeof ApiJobsPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/health': typeof ApiHealthRoute
  '/api/google/callback': typeof ApiGoogleCallbackRoute
  '/api/jobs/pdf': typeof ApiJobsPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/health' | '/api/google/callback' | '/api/jobs/pdf'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/health' | '/api/google/callback' | '/api/jobs/pdf'
  id:
    '__root__' | '/' | '/api/health' | '/api/google/callback' | '/api/jobs/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiGoogleCallbackRoute: typeof ApiGoogleCallbackRoute
  ApiJobsPdfRoute: typeof ApiJobsPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/google/callback': {
      id: '/api/google/callback'
      path: '/api/google/callback'
      fullPath: '/api/google/callback'
      preLoaderRoute: typeof ApiGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/jobs/pdf': {
      id: '/api/jobs/pdf'
      path: '/api/jobs/pdf'
      fullPath: '/api/jobs/pdf'
      preLoaderRoute: typeof ApiJobsPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiGoogleCallbackRoute: ApiGoogleCallbackRoute,
  ApiJobsPdfRoute: ApiJobsPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
